create table SHISHLONOV_MA.regions(
    id_region number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null
);

create table SHISHLONOV_MA.towns(
    id_town number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null ,
    id_region number references SHISHLONOV_MA.regions(id_region)
);

create table SHISHLONOV_MA.medical_organizations(
    id_med_organizations number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null,
    id_town number references SHISHLONOV_MA.towns(id_town)
);

create table SHISHLONOV_MA.hospitals(
    id_hospital number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100)not null,
    id_med_organization number references SHISHLONOV_MA.medical_organizations(id_med_organizations)
);
alter table SHISHLONOV_MA.hospitals
add areas number references SHISHLONOV_MA.area(id_area);
add hospital_tipe number references SHISHLONOV_MA.hospital_tipe;
add schedule number references SHISHLONOV_MA.schedule(id_schedule);
alter table SHISHLONOV_MA.hospitals
add medical_organization number references shishlonov_ma.medical_organizations(id_med_organizations);

create table SHISHLONOV_MA.area
(
    id_area number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name    varchar2(100) not null,
    id_town number references SHISHLONOV_MA.towns
);
create table SHISHLONOV_MA.types_of_years(
    id_types_of_years number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
        name varchar2(100) not null
);
alter table SHISHLONOV_MA.types_of_years
add id_year number references SHISHLONOV_MA.YEARS(id_year);

create table SHISHLONOV_MA.specialities(
    id_speciality number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100)not null ,
    id_hospital number references SHISHLONOV_MA.hospitals(id_hospital),
    id_types_of_years number references SHISHLONOV_MA.types_of_years(id_types_of_years),
    id_gender number references SHISHLONOV_MA.GENDER(id_gender)
);



create table SHISHLONOV_MA.years(
    id_year number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name number not null,
    id_speciality number references SHISHLONOV_MA.types_of_years(id_types_of_years)
);

create table SHISHLONOV_MA.gender(
    id_gender number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null
);


create table SHISHLONOV_MA.technical_works(
    id_technicalworks number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name timestamp not null,
    id_hospital number references SHISHLONOV_MA.hospitals(id_hospital)
);

create table SHISHLONOV_MA.hospital_tipe(
    id_hospital_works number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null,
    id_hospital number references SHISHLONOV_MA.hospitals
);

create table SHISHLONOV_MA.doctors(
    id_doctor number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null,
    doctor_degree number references SHISHLONOV_MA.doctor_degree(id_doctor_degree) not null,
    speciality number references SHISHLONOV_MA.specialities(id_speciality) not null,
    hospital number references  SHISHLONOV_MA.hospitals(id_hospital) not null
);



create table SHISHLONOV_MA.doctor_degree(
    id_doctor_degree number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null
);

create table SHISHLONOV_MA.registration_coupons(
    status char(1) not null ,
    id_registration_coupon number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    id_doctor number references SHISHLONOV_MA.doctors(id_doctor)
);

create table SHISHLONOV_MA.registers(
    id_register number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name date,
    status varchar2(100) not null,
    id_patient number references SHISHLONOV_MA.patients(id_patient) not null,
    status_registr_coupons number references SHISHLONOV_MA.registration_coupons(id_registration_coupon)
);

create table SHISHLONOV_MA.accounts(
    id_account number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    name varchar2(100) not null
);

create table SHISHLONOV_MA.patients(
    id_patient number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    first_name varchar2(100) not null ,
    last_name varchar2(100)not null ,
    middle_name varchar2(100) null,
    date_of_birth date not null ,
    document varchar2(100) not null ,
    gender number references SHISHLONOV_MA.gender(id_gender),
    telephone_number integer null,
    id_area number references SHISHLONOV_MA.area(id_area),
    id_account number references SHISHLONOV_MA.accounts(id_account)
);



create table SHISHLONOV_MA.schedule(
    id_schedule number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    weekday number references SHISHLONOV_MA.weekdays(id_weekday),
    weekend number references SHISHLONOV_MA.weekends(id_weekend)
);

create table SHISHLONOV_MA.weekdays(
    id_weekday number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    open varchar2(100) not null
);

create table SHISHLONOV_MA.weekends(
    id_weekend number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    open varchar2(100) null
);

create table SHISHLONOV_MA.attributes_for_a_doctor(
    id_attributes number generated by default as identity
        (start with 1 maxvalue 999999999 minvalue 1 nocycle nocache noorder) primary key,
    education varchar2(100) not null,
    doctor_degree varchar(100) not null,
    salary number not null,
    rating number not null,
    reviews number not null,
    id_doctor number references shishlonov_ma.doctors(id_doctor) not null
);

