insert into SHISHLONOV_MA.REGIONS (id_region, name)  values (default, 'Кемеровская обл');
insert into SHISHLONOV_MA.REGIONS (ID_REGION, NAME) VALUES (default, 'Красноярская обл');
insert into SHISHLONOV_MA.REGIONS (ID_REGION, NAME) VALUES (default, 'Томская обл');


insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Кемерово', 1);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Таштагол', 1);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Прокопьевск', 1);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Красноярск', 2);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Норильск', 2);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Лесосибирск', 2);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Томск', 3);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Северск', 3);
insert into SHISHLONOV_MA.TOWNS (ID_TOWN, NAME, ID_REGION) VALUES (default, 'Белый Яр', 3);


insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) values (default, 'Кемеровский филиал', 7);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Таштагольский филиал', 8);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) values (default, 'Прокопьевский филиал', 9);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Красноярский филиал',10);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) values (default, 'Норильский филиал', 11);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Лесосибирский филиал', 12);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Томский филиал', 13);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Северский филиал', 14);
insert into SHISHLONOV_MA.MEDICAL_ORGANIZATIONS (ID_MED_ORGANIZATIONS, NAME, ID_TOWN) VALUES (default, 'Белый Яр филиал', 15);

insert into SHISHLONOV_MA.WEEKDAYS(ID_WEEKDAY, OPEN) values (default, 'Понедельник 9:00-18:00');
insert into SHISHLONOV_MA.WEEKDAYS(ID_WEEKDAY, OPEN) values (default, 'Вторник 9:00-18:00');
insert into SHISHLONOV_MA.WEEKDAYS(ID_WEEKDAY, OPEN) values (default, 'Среда 9:00-18:00');
insert into SHISHLONOV_MA.WEEKDAYS(ID_WEEKDAY, OPEN) values (default, 'Четверг 9:00-18:00');
insert into SHISHLONOV_MA.WEEKDAYS(ID_WEEKDAY, OPEN) values (default, 'Пятница 9:00-18:00');

insert into SHISHLONOV_MA.WEEKENDS(ID_WEEKEND, OPEN) values (default, 'Суббота 9:00-17:00');
insert into SHISHLONOV_MA.WEEKENDS(ID_WEEKEND, OPEN) values (default, 'Воскресенье 10:00-16:00');

insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (6, 3);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (7, 4);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (8, 3);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (9, 4);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (10, 3);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (11, 4);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (12, 3);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (13, 4);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (14, 3);
insert into  SHISHLONOV_MA.SCHEDULE(WEEKDAY, WEEKEND) VALUES (15, 4);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №5', 43, 16, 43);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №37', 43, 25, 43);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №81', 44, 17, 44);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №90', 44, 16, 44);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №7', 45, 18, 45);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №43', 45, 17, 45);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №4', 46, 19, 46);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №99', 46, 18, 46);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №6', 47, 20, 47);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №14', 47, 19, 47);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №8', 48, 21, 48);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №15', 48, 20, 48);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №8', 49, 22, 49);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №15', 49, 21, 49);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №17', 50, 23, 50);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №31', 50, 22, 50);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №9', 51, 24, 51);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION) VALUES ('Поликлиника №45', 51, 23, 51);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №64', 44, 17, 44, 1, 1);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №42', 44, 16, 44, 2, 2);

INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №21', 45, 17, 45, 2, 4);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №8', 46, 19, 46, 1, 5);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №87', 46, 18, 46, 2, 6);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №62', 48, 21, 48, 1, 9);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №11', 48, 20, 48, 2, 10);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №9', 49, 22, 49, 1, 11);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) VALUES ('Поликлиника №16', 49, 21, 49, 2, 12);
INSERT INTO SHISHLONOV_MA.HOSPITALS(name, id_med_organization, schedule, medical_organization, hospital_tipe, areas) values ('Поликлиника №19', 50, 23, 50, 1, 13);

insert into SHISHLONOV_MA.HOSPITALS(NAME, HOSPITAL_TIPE, AREAS) values (43, 1, 2);
INSERT INTO SHISHLONOV_MA.HOSPITALS(NAME, ID_MED_ORGANIZATION, SCHEDULE, MEDICAL_ORGANIZATION, HOSPITAL_TIPE, AREAS) VALUES ('Поликлиника №70', 45, 18, 45, 1, 2);

insert into SHISHLONOV_MA.HOSPITAL_TIPE(ID_HOSPITAL_WORKS, NAME) values (default, 'государственная');
insert into SHISHLONOV_MA.HOSPITAL_TIPE(ID_HOSPITAL_WORKS, NAME) values (default, 'частная');
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('area1', 16);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('area2', 16);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок3', 17);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок4', 17);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок5', 18);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок6', 18);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок7', 19);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок8', 19);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок9', 20);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок10', 20);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок11', 21);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок12', 21);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок13', 22);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок14', 22);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок15', 23);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок16', 23);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок17', 24);
insert into SHISHLONOV_MA.AREA(NAME, ID_TOWN) VALUES ('участок18', 24);

insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 3);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 5);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 7);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 10);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 12);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 14);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 17);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 18);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 20);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 23);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 27);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 29);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 32);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 36);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 42);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 49);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 56);
insert into SHISHLONOV_MA.YEARS(ID_YEAR, NAME) values (default, 68);

insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Раннее детство', 1);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Дошкольный', 2);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Школьный возраст', 4);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Подростковый', 6);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Юность', 7);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Средний возраст', 10);
insert into SHISHLONOV_MA.TYPES_OF_YEARS(ID_TYPES_OF_YEARS, NAME, ID_YEAR) values (default, 'Пожилые люди', 18);

insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Гематология', 43, 1, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Гематология', 44, 1, 2);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Генетика', 45, 2, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Генетика', 46, 2, 2);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Дерматовенерология', 52, 3, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Дерматовенерология', 53, 3, 2);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Кардиология', 54, 4, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Кардиология', 55, 4, 2);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Неврология', 56, 5, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Неврология', 57, 5, 2);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Гематология', 58, 6, 1);
insert into SHISHLONOV_MA.SPECIALITIES(ID_SPECIALITY, NAME, ID_HOSPITAL, ID_TYPES_OF_YEARS, ID_GENDER) VALUES (default, 'Гематология', 59, 6, 2);

insert into SHISHLONOV_MA.GENDER(ID_GENDER, NAME) values (default, 'Мужской');
insert into SHISHLONOV_MA.GENDER(ID_GENDER, NAME) values (default, 'Женский');

insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'fweff@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'wthyej@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'uykrsdf@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'wemth@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'cvhu@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'oyip@mail.ru');
insert into SHISHLONOV_MA.ACCOUNTS(ID_ACCOUNT, NAME) values (default, 'wfewf@mail.ru');

insert into SHISHLONOV_MA.PATIENTS(ID_ACCOUNT,FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA)
    VALUES (default, 'Гришин', 'Илья', 'Алексеевич', '11/04/1964', 'Паспорт', 1, '89894645', 4);
insert into SHISHLONOV_MA.PATIENTS(ID_PATIENT, FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA, ID_ACCOUNT)
 VALUES (DEFAULT, 'Серов', 'Валерий', 'Викторович', '01/01/1950', 'СНИЛС', 1, 8903455, 2, 2);
insert into SHISHLONOV_MA.PATIENTS(ID_PATIENT, FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA, ID_ACCOUNT)
    values (default, 'Миронов', 'Михаил', 'Анатольевич', '23/04/1973', 'Паспорт', 1, '8904535345', 3, 3);
insert into SHISHLONOV_MA.PATIENTS(ID_PATIENT, FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA, ID_ACCOUNT)
    values (default, 'Жаркова', 'Алла', 'Юрьевна', '05/12/1964', 'СНИЛС', 2, '8904534535', 4, 4);
insert into SHISHLONOV_MA.PATIENTS(ID_PATIENT, FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA, ID_ACCOUNT)
    values (default, 'Демчук', 'Ольга', 'Викторовна', '10/10/1971', 'Паспорт', 2, '8904535345', 5, 5);
insert into SHISHLONOV_MA.PATIENTS(ID_PATIENT, FIRST_NAME, LAST_NAME, MIDDLE_NAME, DATE_OF_BIRTH, DOCUMENT, GENDER, TELEPHONE_NUMBER, ID_AREA, ID_ACCOUNT)
    values (default, 'Вагапова', 'Ирина', 'Ахметовна', '21/03/1945', 'Паспорт', 2, '890234235', 6, 6);

insert into SHISHLONOV_MA.DOCTOR_DEGREE(ID_DOCTOR_DEGREE, NAME) values (default, 'Первая');
insert into SHISHLONOV_MA.DOCTOR_DEGREE(ID_DOCTOR_DEGREE, NAME) values (default, 'Вторая');
insert into SHISHLONOV_MA.DOCTOR_DEGREE(ID_DOCTOR_DEGREE, NAME) values (default, 'Третья');
insert into SHISHLONOV_MA.DOCTOR_DEGREE(ID_DOCTOR_DEGREE, NAME) values (default, 'Высшая');

insert into SHISHLONOV_MA.DOCTORS (ID_DOCTOR, NAME, DOCTOR_DEGREE, SPECIALITY, HOSPITAL) VALUES (default, 'Герасимов', 1, 3, 43);
insert into SHISHLONOV_MA.DOCTORS (ID_DOCTOR, NAME, DOCTOR_DEGREE, SPECIALITY, HOSPITAL) VALUES (default, 'Шкадова', 2, 4, 44);
insert into SHISHLONOV_MA.DOCTORS (ID_DOCTOR, NAME, DOCTOR_DEGREE, SPECIALITY, HOSPITAL) VALUES (default, 'Варламова', 3, 5, 45);
insert into SHISHLONOV_MA.DOCTORS (ID_DOCTOR, NAME, DOCTOR_DEGREE, SPECIALITY, HOSPITAL) VALUES (default, 'Кокарев', 4, 7, 46);
insert into SHISHLONOV_MA.DOCTORS (ID_DOCTOR, NAME, DOCTOR_DEGREE, SPECIALITY, HOSPITAL) VALUES (default, 'Герасимов', 1, 9, 52);

insert into SHISHLONOV_MA.REGISTRATION_COUPONS(ID_REGISTRATION_COUPON, STATUS, ID_DOCTOR) VALUES (default, 1, 1);
insert into SHISHLONOV_MA.REGISTRATION_COUPONS(ID_REGISTRATION_COUPON, STATUS, ID_DOCTOR) VALUES (default, 0, 2);
insert into SHISHLONOV_MA.REGISTRATION_COUPONS(ID_REGISTRATION_COUPON, STATUS, ID_DOCTOR) VALUES (default, 1, 3);
insert into SHISHLONOV_MA.REGISTRATION_COUPONS(ID_REGISTRATION_COUPON, STATUS, ID_DOCTOR) VALUES (default, 0, 4);
insert into SHISHLONOV_MA.REGISTRATION_COUPONS(ID_REGISTRATION_COUPON, STATUS, ID_DOCTOR) VALUES (default, 1, 5);

insert into SHISHLONOV_MA.REGISTERS(ID_REGISTER, NAME, STATUS, ID_PATIENT, STATUS_REGISTR_COUPONS) VALUES (default, '01/09/2021', 1, 2, 1);
insert into SHISHLONOV_MA.REGISTERS(ID_REGISTER, NAME, STATUS, ID_PATIENT, STATUS_REGISTR_COUPONS) VALUES (default, '01/09/2021', 1, 3, 2);
insert into SHISHLONOV_MA.REGISTERS(ID_REGISTER, NAME, STATUS, ID_PATIENT, STATUS_REGISTR_COUPONS) VALUES (default, '01/09/2021', 0, 4, 3);
insert into SHISHLONOV_MA.REGISTERS(ID_REGISTER, NAME, STATUS, ID_PATIENT, STATUS_REGISTR_COUPONS) VALUES (default, '02/09/2021', 1, 5, 4);
insert into SHISHLONOV_MA.REGISTERS(ID_REGISTER, NAME, STATUS, ID_PATIENT, STATUS_REGISTR_COUPONS) VALUES (default, '02/09/2021', 0, 5, 5);

insert into SHISHLONOV_MA.ATTRIBUTES_FOR_A_DOCTOR(ID_ATTRIBUTES, EDUCATION, DOCTOR_DEGREE, SALARY, RATING, REVIEWS, ID_DOCTOR) VALUES (default, 'высшее', 'первая', 15000, 4, 10, 1);
insert into SHISHLONOV_MA.ATTRIBUTES_FOR_A_DOCTOR(ID_ATTRIBUTES, EDUCATION, DOCTOR_DEGREE, SALARY, RATING, REVIEWS, ID_DOCTOR) VALUES (default, 'высшее', 'вторая', 18000, 3, 12, 2);
insert into SHISHLONOV_MA.ATTRIBUTES_FOR_A_DOCTOR(ID_ATTRIBUTES, EDUCATION, DOCTOR_DEGREE, SALARY, RATING, REVIEWS, ID_DOCTOR) VALUES (default, 'высшее', 'третья', 25000, 7, 15, 3);
insert into SHISHLONOV_MA.ATTRIBUTES_FOR_A_DOCTOR(ID_ATTRIBUTES, EDUCATION, DOCTOR_DEGREE, SALARY, RATING, REVIEWS, ID_DOCTOR) VALUES (default, 'высшее', 'третья', 35000, 1, 18, 4);
insert into SHISHLONOV_MA.ATTRIBUTES_FOR_A_DOCTOR(ID_ATTRIBUTES, EDUCATION, DOCTOR_DEGREE, SALARY, RATING, REVIEWS, ID_DOCTOR) VALUES (default, 'высшее', 'высшая', 50000, 2, 6, 5);

select * from SHISHLONOV_MA.WEEKDAYS, SHISHLONOV_MA.WEEKENDS;
select * from SHISHLONOV_MA.MEDICAL_ORGANIZATIONS;
select * from SHISHLONOV_MA.SCHEDULE;
select * from SHISHLONOV_MA.HOSPITALS;
select * from SHISHLONOV_MA.PATIENTS;

--select
--     dbms_random.random() as "random"
--from dual;



SELECT * FROM SHISHLONOV_MA.MEDICAL_ORGANIZATIONS

--delete from MEDICAL_ORGANIZATIONS
--where ID_MED_ORGANIZATIONS <19;